import React from "react";
import {
  IconAccessible,
  IconArmchair,
  IconBabyCarriage,
  IconBallTennis,
  IconBarbell,
  IconBath,
  IconBeach,
  IconBike,
  IconBook,
  IconBooks,
  IconBuildingBridge2,
  IconBuildingChurch,
  IconBusinessplan,
  IconCampfire,
  IconCandy,
  IconCarGarage,
  IconCards,
  IconChargingPile,
  IconChess,
  IconClock24,
  IconClockBolt,
  IconCreditCard,
  IconCup,
  IconCurrencyDollar,
  IconDeviceCctv,
  IconDeviceGamepad,
  IconDeviceTv,
  IconDoor,
  IconDroplet,
  IconElevator,
  IconFireExtinguisher,
  IconFirstAidKit,
  IconFish,
  IconFlame,
  IconGift,
  IconGlass,
  IconGolf,
  IconGrill,
  IconHanger,
  IconHeartHandshake,
  IconHearts,
  IconIroning,
  IconKayak,
  IconKey,
  IconLockSquareRounded,
  IconLuggage,
  IconMap2,
  IconMassage,
  IconMicrophone,
  IconMicrophone2,
  IconMountain,
  IconMusic,
  IconNews,
  IconPaperBag,
  IconParking,
  IconParkingCircle,
  IconPaw,
  IconPicnicTable,
  IconPlane,
  IconPlant2,
  IconPlayHandball,
  IconPool,
  IconPresentation,
  IconPrinter,
  IconBellFilled,
  IconScan,
  IconScissors,
  IconScubaDiving,
  IconShoppingBag,
  IconSmoking,
  IconSmokingNo,
  IconSnowflake,
  IconSun,
  IconSwimming,
  IconTicket,
  IconToolsKitchen2,
  IconUserCheck,
  IconUsers,
  IconVolumeOff,
  IconWash,
  IconWifi,
  IconYoga,
  IconPoint,
  IconMapPin,
} from "@tabler/icons-react";

type TablerIconComponent = React.ComponentType<{
  size?: number;
  stroke?: number;
  className?: string;
}>;

const iconMap: Record<string, TablerIconComponent> = {
  accessible: IconAccessible,
  armchair: IconArmchair,
  "baby-carriage": IconBabyCarriage,
  "ball-tennis": IconBallTennis,
  barbell: IconBarbell,
  bath: IconBath,
  beach: IconBeach,
  bike: IconBike,
  book: IconBook,
  books: IconBooks,
  "building-bridge-2": IconBuildingBridge2,
  "building-church": IconBuildingChurch,
  businessplan: IconBusinessplan,
  campfire: IconCampfire,
  candy: IconCandy,
  "car-garage": IconCarGarage,
  cards: IconCards,
  "charging-pile": IconChargingPile,
  chess: IconChess,
  "clock-24": IconClock24,
  "clock-bolt": IconClockBolt,
  "credit-card": IconCreditCard,
  cup: IconCup,
  "currency-dollar": IconCurrencyDollar,
  "device-cctv": IconDeviceCctv,
  "device-gamepad": IconDeviceGamepad,
  "device-tv": IconDeviceTv,
  door: IconDoor,
  droplet: IconDroplet,
  elevator: IconElevator,
  "fire-extinguisher": IconFireExtinguisher,
  "first-aid-kit": IconFirstAidKit,
  fish: IconFish,
  flame: IconFlame,
  gift: IconGift,
  glass: IconGlass,
  golf: IconGolf,
  grill: IconGrill,
  hanger: IconHanger,
  "heart-handshake": IconHeartHandshake,
  hearts: IconHearts,
  ironing: IconIroning,
  kayak: IconKayak,
  key: IconKey,
  "lock-square-rounded": IconLockSquareRounded,
  luggage: IconLuggage,
  "map-2": IconMap2,
  massage: IconMassage,
  microphone: IconMicrophone,
  "microphone-2": IconMicrophone2,
  mountain: IconMountain,
  music: IconMusic,
  news: IconNews,
  "paper-bag": IconPaperBag,
  parking: IconParking,
  "parking-circle": IconParkingCircle,
  paw: IconPaw,
  "picnic-table": IconPicnicTable,
  plane: IconPlane,
  "plant-2": IconPlant2,
  "play-handball": IconPlayHandball,
  pool: IconPool,
  presentation: IconPresentation,
  printer: IconPrinter,
  "bell-filled": IconBellFilled,
  scan: IconScan,
  scissors: IconScissors,
  "scuba-diving": IconScubaDiving,
  "shopping-bag": IconShoppingBag,
  smoking: IconSmoking,
  "smoking-no": IconSmokingNo,
  snowflake: IconSnowflake,
  sun: IconSun,
  swimming: IconSwimming,
  ticket: IconTicket,
  "tools-kitchen-2": IconToolsKitchen2,
  "user-check": IconUserCheck,
  users: IconUsers,
  "volume-off": IconVolumeOff,
  wash: IconWash,
  wifi: IconWifi,
  yoga: IconYoga,
};

export function getTablerIcon(
  iconName: string | null | undefined,
  size = 18,
  stroke = 1.5,
): React.ReactElement {
  if (!iconName) return <IconPoint size={size} stroke={stroke} />;
  const cleanName = iconName.replace("-filled", "");
  const Icon = iconMap[cleanName];
  if (Icon) return <Icon size={size} stroke={stroke} />;
  return <IconPoint size={size} stroke={stroke} />;
}

export function getAttractionIcon(
  iconName: string | null | undefined,
  size = 18,
  stroke = 1.5,
): React.ReactElement {
  if (!iconName) return <IconMapPin size={size} stroke={stroke} />;
  const cleanName = iconName.replace("-filled", "");
  const Icon = iconMap[cleanName];
  if (Icon) return <Icon size={size} stroke={stroke} />;
  return <IconMapPin size={size} stroke={stroke} />;
}
